version: '2'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    # ports:
    #   - 8080:80
    volumes:
      - $PWD/docker-data/storage:/var/www/storage
    working_dir: /var/www
    environment:
      ElASTICSEARCH_HOST: elasticsearch.datapirates.ir
      APP_NAME: 'Market Sample'
      APP_ENV: production
      APP_KEY: 'base64:uo+AM3CENeN1wGAzl/beafvBExUasvWtWng5P1ZSSyo='
      APP_DEBUG: 0
      APP_URL: 'http://localhost:8080'
      JWT_SECRET: 'Q4bZZVKjnceDya2uZGJrEdFs56pV9sbM3kTCWJfwowUWf45RX8BKf0hP79C5lKhd'
      LOG_CHANNEL: stderr
      LOG_STDERR_LEVEL: info
      DB_CONNECTION: mysql
      DB_HOST: 'db'
      DB_PORT: 3306
      DB_DATABASE: laravel_db
      DB_USERNAME: root
      DB_PASSWORD: password_abc
    labels:
      - "traefik.frontend.rule=Host:market-sample.datapirates.ir"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_default"
    networks:
      app_internal:
      traefik_default:
  db:
    image: mysql:5.7
    volumes:
      - ./docker-data/db:/var/lib/database
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: password_abc
    networks:
      app_internal:
  redis:
    image: redis
    volumes:
      - ./docker-data/redis:/data
    networks:
      app_internal:

networks:
  app_internal:
  traefik_default:
    external: true
